addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get install -y pkg-config libcairo2-dev libjpeg8-dev libgif-dev
  - createdb template_postgis
  - psql -c "CREATE EXTENSION postgis" template_postgis

env:
  - NPROCS=1 JOBS=1 PGUSER=postgres

language: node_js
node_js:
  - "0.8"
  - "0.10"

notifications:
  irc:
    channels:
      - "irc.freenode.org#cartodb"
    use_notice: true
